/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.Cliente;
import DAL.Gestao;
import DAL.ProdVenda;
import DAL.Venda;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class produtoVenda extends javax.swing.JPanel {

    private login janelaPrincipal;
    private Venda procura = new Venda();
    private Gestao gestor = new Gestao();
    private static final String Persistence_UNIT_NAME = "projetoUltimoPU";
    private static EntityManagerFactory factory;
    
    
    public produtoVenda(login parent,Venda recebida,Gestao gestor) {
        initComponents();
        janelaPrincipal = parent;
        procura = recebida;
        
        this.gestor=gestor;
        
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        factory = Persistence.createEntityManagerFactory(Persistence_UNIT_NAME);
        EntityManager em = factory.createEntityManager();
        
        Query q = em.createNamedQuery("ProdVenda.findByCodVenda");
        q.setParameter("codVenda",procura.getCodVenda());
        //List<ProdVenda> listaProdutos= null;
        
        for (Object d : q.getResultList()) {
            if ((((ProdVenda) d).getProdVendaPK().getCodVenda()==procura.getCodVenda())) {
                //listaProdutos.add((ProdVenda )d);
                model.addRow(new Object[]{((ProdVenda )d).getProdVendaPK().getCodProduto(),((ProdVenda )d).getProdutoFinal().getNomeProduto(),((ProdVenda )d).getQuantidade(),((ProdVenda )d).getProdutoFinal().getPreco(),((ProdVenda )d).getQuantidade()*((ProdVenda )d).getProdutoFinal().getPreco()});
            }
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(36, 64, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "quantidade", "preço/uni", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 630, 270));

        jButton1.setText("voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oceano.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 410));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VENDA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 590, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, -1, 360));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(gestor.getIdDepartamento()==1) this.janelaPrincipal.trocaPainel(new menuGestorVenda2b(janelaPrincipal,procura,gestor));
        if(gestor.getIdDepartamento()==2) this.janelaPrincipal.trocaPainel(new menuGestorArmazem(janelaPrincipal,procura,gestor));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
